### ISSUE TITLE
Parser doesn't preserve multi-line search indentation

### ISSUE THREAD

**Issue by cschmidt0121** [splunk/addonfactory-splunk-conf-parser-lib#99]
When working with long searches with joins, it can be useful to indent subsearches to make it easier to follow the search:

```
index=foo
| join type=outer my_field [|makeresults
  | eval thing="a"
  | eval another_thing="b"]
| table my_field thing another_thing
```

The above example, when parsed by the module, loses all indentation leaving you with 

```
index=foo
| join type=outer my_field [|makeresults
| eval thing="a"
| eval another_thing="b"]
| table my_field thing another_thing
```

Would there be any way for this module to support this sort of indentation?

**Comment by artemrys** [comment]
hey @cschmidt0121
thanks for submitting an issue
I doubt there is any Python library specific to Splunk SPL that we can use to support this

**Comment by cschmidt0121** [comment]
Okay, no worries. I believe it's supported by Splunk's internal cli_common module but I understand thats an entirely different codebase. Thank you anyways!

**Comment by kundeng** [comment]
doesn't parse its own db_inputs.conf correctly.  Useless.
